[package]
name = "libretro-rs"
description = "High-level abstractions for the libretro API"
readme = "README.md"
repository = "https://github.com/libretro-rs/libretro-rs"
license = "MIT/Apache-2.0"
version = "0.1.3"
authors = ["Adam Becker <im.adam.becker@gmail.com>"]
edition = "2018"
exclude = [
  ".devcontainer"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
libretro-rs-ffi = { path = "../libretro-rs-ffi" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
